---
Name: nswdpc-versioned-record-discovery
Only:
  moduleexists: silverstripe/cms
---
NSWDPC\Utilities\VersionedRecordDiscovery\UnpublishedRecordReport:
  default_target_model: 'SilverStripe\CMS\Model\SiteTree'
  restrict_to_models:
    - 'SilverStripe\CMS\Model\SiteTree'
